services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    ports:
      - "5001:5001"
      - "8080:8080"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8545:8545"
    volumes:
      - ./shared:/shared
    environment:
      - HARDHAT_NETWORK=localhost

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./shared:/app/public/shared
    depends_on:
      - backend
      - mongo
      - ipfs

volumes:
  mongo_data:
